### ISSUE TITLE
What drives the choice of IQR vs MAD?

### ISSUE THREAD

**Issue by SamGG** [giannimonaco/flowAI#19]
Hi,

I don't catch the rational of IQR, especially because it is not adjusted when comparing to MAD. Could you explain me what IQR brings over MAD?

```
> x = rnorm(100000)
> mad(x)
[1] 1.003071
> IQR(x)
[1] 1.352785
```

**Comment by giannimonaco** [comment]
Hi,
IQR is just less sensitive as it has a higher threshold when detecting the
anomalies. It does not really bring anything else..

**Comment by SamGG** [comment]
Thanks for your answer.
So, IIUC, it is just about changing the level of significance.
IMHO, alpha is a better choice for tuning. #20
