### ISSUE TITLE
Wrong test?

### ISSUE THREAD

**Issue by SamGG** [giannimonaco/flowAI#20]
I think the test does not match the message.
https://github.com/giannimonaco/flowAI/blob/2af15bdabc0416e9e63882cea6f6fd16557e0872/R/anomaly-detection.R#L65-L67

**Comment by giannimonaco** [comment]
Thank you for spotting this. I appreciate it!
I fixed the if statement.

**Comment by SamGG** [comment]
Thanks for your feedback.
I think that even alpha = 0.1 is too permissive because it is equivalent to stating 0.1 outlier among N random numbers from a gaussian distribution.
