### ISSUE TITLE
cytoset support

### ISSUE THREAD

**Issue by DillonHammill** [giannimonaco/flowAI#3]
@giannimonaco, I am going through and tidying up all the code in CytoExploreR and it would be great if flow_auto_qc() worked with the new `cytoset` class in flowWorkspace. The changes I suggested have allowed the code to run with these objects but it looks like there is a separate issue in flow_margin_check() that is preventing flow_auto_qc() from succeeding:
```{r}
library(CytoExploreRData)
library(flowWorkspace)

# flowSets work fine
fs <- Activation
cs_clean <- flow_auto_qc(fs[1:4],
                         html_report = FALSE,
                         mini_report = FALSE,
                         fcs_QC = FALSE,
                         folder_results = FALSE)

# cytosets come up stuck
cs <- flowSet_to_cytoset(fs)
cs_clean <- flow_auto_qc(cs[1:4],
                         html_report = FALSE,
                         mini_report = FALSE,
                         fcs_QC = FALSE,
                         folder_results = FALSE)

Error in x@exprs[, parms, drop = FALSE] : 
  no 'dimnames' attribute for array
```

I am using the latest versions of cytolib, flowCore and flowWorkspace. Are you able to take a look at this? I have to do some flowSet conversions to get this code to work and would like to remove these if possible.

Cheers,
Dillon

**Comment by giannimonaco** [comment]
Hi Dillon,

I tried running flowAI with a cytoset dataset on my laptop, and it seemed
it worked fine!

I attached a screenshot that also contains the versions of the packages I
have.

Let me know if you tried with different versions.

Cheers,
Gianni


[image: Screen Shot 2020-08-25 at 1.06.26 PM.png]

**Comment by DillonHammill** [comment]
Thanks @giannimonaco, I can't seem to open the image, but I can try again tomorrow.

**Comment by giannimonaco** [comment]
Hi @DillonHammill,
I double-checked the issue and after updating all packages I also got the error. I checked the flow margin check function and I fixed the issue by using exprs(x) instead of x@exprs.
The updated version is already on git hub and it should be in Bioconductor tomorrow I think.
