### ISSUE TITLE
Min and Max Range formatted as characters instead of double

### ISSUE THREAD

**Issue by timmocking** [giannimonaco/flowAI#5]
A small suggestion: flowAI converts the Min and Max range as defined in the .FCS parameters to characters. This is normally not an issue, as saving the .FCS re-converts these to doubles. However, if you run an additional anomaly detection algorithm after running flowAI, the output is erroneous because of this. 

```
library(flowAI)
library(flowCore)

ff <- read.FCS(FILE)
ff <- flow_auto_qc(ff, output=2)

meta <- flowWorkspace::pData(flowCore::parameters(ff))
typeof(meta['FSC-A', 'minRange'])
```

**Comment by giannimonaco** [comment]
Hi!
Thank you for reporting this! You are right, the Min and Max range values
were converted to characters for output=2.
I just fixed it. Just use the github version if you need the fixed version
soon.
