### ISSUE TITLE
flow_auto_qc() returns flowFrame named "V1"

### ISSUE THREAD

**Issue by BexMillard** [giannimonaco/flowAI#6]
Hi, thanks for your time developing the flowAI package.

I noticed that when applying the flow_auto_qc() function to a flowFrame the output flowFrame no longer has its original sample name/identifier which is instead replaced by "V1". This does not seem to be an issue for flowSets.

> identifier(ff)    # flowFrame loaded with read.FCS()
[1] "Batch0_s01.fcs"
> identifier(ff_qc)    # flow_auto_qc() output
[1] "V1"

To prevent flow_auto_qc() flowFrame outputs from being accidentally overwritten would it be possible to assign the original sample names/identifiers back to the flow_auto_qc() flowFrame output as is done for flowSets?

This would also be useful for distinguishing flowFrame QC results in the summary.txt output as all applications of the flow_auto_qc() function to individual flowFrames will currently be listed under the same filename "V1".

**Comment by giannimonaco** [comment]
Hi! 
Thank you for the suggestion!
You are right that flowAI was not keeping the original names from flowFrame objects.
I just fixed it now.

**Comment by BexMillard** [comment]
Thanks for the fix @giannimonaco!
