### ISSUE TITLE
flow_auto_qc() creates QC file with wrong file name

### ISSUE THREAD

**Issue by phauchamps** [giannimonaco/flowAI#8]
Hi dear flowAI team,

I noticed that when I launch flow_auto_qc() with 1.24 version of flowAI, and ouput parameter = 1, the QC fcs file that is generated in the 'resultsQC' directory is wrongly named after 'V1_QC' instead of 'myfilename_QC'. 

Does this issue sound familiar to you ? 

Thanks,

Philippe

**Comment by giannimonaco** [comment]
Hi Philippe,

Thank you. Yes, I know the issue. The version 1.25.2 that you find on
github (or the bioconductor developmental branch) already includes the fix.

Best wishes,
Gianni

**Comment by phauchamps** [comment]
Thank you Gianni,

Looking into the closed issues first would have saved us both some time, sorry for that ;-)

Best wishes,
Philippe.

**Comment by giannimonaco** [comment]
No problems! :)
Cheers,
Gianni
